imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    translator:
        fallback:           en

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    autoescape: false

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
        
sonata_admin:
    title:      " "
    title_logo: bundles/cgcadmin/images/logo.png
    
sonata_media:
    # if you don't use default namespace configuration
    #class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    default_context: default
    db_driver: doctrine_orm
    providers:
        image:
            resizer: sonata.media.resizer.custom
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 84, height: 84, quality: 100}
                medium: { width: 113, height: 113, quality: 100}
                big:   { width: 500, height: 500, quality: 100}

    cdn:
        server:
            path: /jobs/CGC/web/uploads/media #/uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false
            
sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes
        
sonata_user:
    security_acl: false
    manager_type: orm # can be orm or mongodb
    admin:
        user:
          class:      Application\Sonata\UserBundle\Admin\Model\UserAdmin
    
fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User


    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager
        
sonata_intl:
    timezone:
        default: America/Sao_Paulo
        
sonata_core: ~

ivory_ck_editor:
    default_config: default
    configs:
        default:
            enterMode: 2
#            filebrowserBrowseRoute: admin_sonata_media_media_browser
#            filebrowserImageBrowseRoute: admin_sonata_media_media_browser
#            # Display images by default when clicking the image dialog browse button
#            filebrowserImageBrowseRouteParameters:
#                provider: sonata.media.provider.image
#            filebrowserUploadRoute: admin_sonata_media_media_upload
#            filebrowserUploadRouteParameters:
#                provider: sonata.media.provider.file
#            # Upload file as image when sending a file from the image dialog
#            filebrowserImageUploadRoute: admin_sonata_media_media_upload
#            filebrowserImageUploadRouteParameters:
#                provider: sonata.media.provider.image
#                context: my-context # Optional, to upload in a custom context
                
#coop_tilleuls_ck_editor_sonata_media:
#    templates:
#        layout: CoopTilleulsCKEditorSonataMediaBundle::layout.html.twig # Layout of the file browser
#        browser: CoopTilleulsCKEditorSonataMediaBundle:MediaAdmin:browser.html.twig # Template of the CKEditor file browser
#        upload: CoopTilleulsCKEditorSonataMediaBundle:MediaAdmin:upload.html.twig # Template returned after a direct upload
